title: "Лабораторная работа №1"
author: "Barmin Mikhail"
output: html_document


### Задание 1

1. Сгенерируйте 200 случайных значений из стандартного экспоненциального распределения и
сохраните в вектор exp.1. Найдите среднее и стандартное отклонение из данных этого вектора.

exp.1 <- rexp(n = 200)
mean(exp.1)
sd(exp.1)


2. Повторите, использовав следующие значения параметра λ: 0.1, 0.5, 5, 10, и сохраните
результаты в векторы: exp.0.1, exp.0.5, exp.5, exp.10.

exp.0.1 <-c (rexp(n = 200, rate = 0.1))
mean(exp.0.1)
sd(exp.0.1)

exp.0.5 <- c(rexp(n = 200, rate = 0.5))
mean(exp.0.5)
sd(exp.0.5)

exp.5 <- c(rexp(n = 200, rate = 5))
mean(exp.5)
sd(exp.5)

exp.10 <- c(rexp(n = 200,rate = 10))
mean(exp.10)
sd(exp.10)


3. Функция plot() общая функция для визуализации данных. Функция hist() принимает данные 
и раскладывает их по корзинам. Чтобы использовать эти функции нужно для начала передать 
им данные, которые хотим визуализировать.

4. Используйте функцию hist() для построения гистограммы полученного ранее стандартного
распределения.

hist(exp.1)


5. Используйте функцию plot() с тем же самым вектором для построения графика значений в
порядке следования.

plot(exp.1)


6. Используйте функцию plot() с любыми двумя полученными ранее векторами, чтобы получить
диаграмму рассеяния (scatterplot) этих векторов относительно друг друга.

plot(exp.0.1, exp.0.5)


7. Теперь сравним свойства всех наших векторов. Для начала создадим вектор, содержащий
средние значения каждого из 5 полученных ранее распределений в порядке их создания.
Полученный вектор сохраним в переменную exp.means. Далее необходимо создать следующие
диаграммы рассеяния:

exp.means <- c(mean(exp.1), mean(exp.0.1), mean(exp.0.5), mean(exp.5), mean(exp.10))


8. Вектор с пятью средними относительно каждого из пяти векторов с различными значениями λ.

exp.param <- c(1, 0.1, 0.5, 5, 10)
plot(exp.means, exp.param)


9. Вектор с пятью стандартными отклонениями относительно каждого из пяти векторов с
различными значениями λ.

exp.sds <- c(sd(exp.1), sd(exp.0.1), sd(exp.0.5), sd(exp.5), sd(exp.10))
plot(exp.sds, exp.param)


10. Вектор с пятью средними относительно вектора с пятью стандартными отклонениями.

plot(exp.means, exp.sds)


* Среднее и стандартное отклонения экспоненциального распределения обратно пропорциональны
значению λ.    
Значения среднего и стандартного отклонения имеют прямую линейную зависимость



### Задание 2

R достаточно производителен, чтобы вычислять относительно большие объёмы данных.

1. Для демонстрации сгенерируйте 1100000 (1 млн. 100 тысяч) чисел из стандартного
экспоненциального распределения и сохраните их в вектор huge.exp.1. Получите среднее и
стандартное отклонение.

huge.exp.1 <- c(rexp(n = 1100000))
mean(huge.exp.1)
sd(huge.exp.1)


2. Получите гистограмму huge.exp.1. Она соответствует функции 1 - e:^(-x)? Должна ли?

hist(huge.exp.1)


* Полученный график распределения случайной величины не соответствует графику
соответствующей функции распределения, т.к. в 1 случае - это распределение
случайной величины по экспоненциальному закону, а во втором - функция*


3. Получите среднее всех чисел из huge.exp.1 строго больших 1. Для проверки выборки может
потребоваться новый вектор.

mean(huge.exp.1[huge.exp.1 > 1])


4. Получите матрицу huge.exp.1.mat, содержащую 1100 строк и 1000 колонок. Постройте
гистограмму, использовав полученную матрицу. Что можно сказать о полученных данных?

huge.exp.1.mat <- matrix(huge.exp.1, nrow = 1100, ncol = 1000)
hist(huge.exp.1.mat)


* Гистограмма матрицы соответсвует гистограмме экспоненциального распределения.


5. Рассчитайте среднее 137-й колонки из huge.exp.1.mat.

mean(huge.exp.1.mat[, 137])


6. Найдите среднее всей 1000 колонок и сохраните их в вектор. Отобразите диаграмму средних
зннчений колонок. Объясните почему форма диаграммы отличается от виденных ранее.

huge.exp.1.mat.means <- colMeans(huge.exp.1.mat)
barplot(huge.exp.1.mat.means)


* Потому что в данном случае данные являются другими (средние значения).


7. Рассчитайте квадрат каждого значения из huge.exp.1 и найдите среднее и стандартное
отклонение полученного вектора квадратов. Объясните отличие от соответствующих показателей
вектора huge.exp.1. Вам может помочь формула, по которой R рассчитывает стандартное
отклонение: sqrt(sum((x - mean(x))^2) / (n - 1)).

huge.exp.1.sq <- (huge.exp.1 ^ 2)
huge.exp.1.sq.mean <- mean(huge.exp.1.sq)
huge.exp.1.sq.sd <- sd(huge.exp.1.sq)

print(huge.exp.1.sq.mean)
print(huge.exp.1.sq.sd)


* Среднее и стандартное отклонения увеличиваются с увеличением значений вектора.     
Стандартное отклонение растет быстрее из-за квадрата в формуле его вычисления*