title: "Лабораторная работа №3"
author: "Barmin Mikhail"
output: html_document



### Исходные данные

Файл forbes.htm содержит список богатейших американцев по версии журнала Форбс.



### Задание 1


1. Используйте команду readLines для загрузки файла в текстовый вектор html.

html <- readLines('https://raw.githubusercontent.com/SergeyMirvoda/MD-DA-2017/master/data/forbes.htm')


Сколько строк в файле?

length(html) # 1991 строка

Сколько символов в файле?

sum(nchar(html)) # 80380 символов


2. Откройте файл в текстовом редакторе. Найдите строки, содержащие данные о Билле Гейтсе и Ларри Эллисоне и
запомните размер их дохода.

* Bill Gates 72 B 
* Larry Ellison 41 B


3. Напишите шаблон регулярного выражения и используйте функцию grep, чтобы извлечь размер дохода из данных в
векторе html. Удостоверьтесь, что полученный вектор номеров строк содержит содержит ровно 100 записей и
ссылается на номера строк в котрых действительно есть информация о доходе, а не просто первый попавшийся текст.

finance <- grep("\\$\\d{1,},\\d{1,} B|\\$\\d{1,} B", html)
finance

length(finance)


4. Напишите код, использовав регулярное выражение из п. 3, и функции regexp и regmatches, чтобы извлечь все
данные о доходе. Проверьте следующее:

finance.p <- regexpr("\\$\\d{1,},\\d{1,} B|\\$\\d{1,} B", html)
finance.m <- regmatches(html,finance.p)
finance.m


Должно быть ровно сто значений.

length(finance.m)

Самый большой доход должен быть доход Билла Гейтса

finance.m[1]

Такой доход должен быть в списке один раз.

finance.m[finance.m == "$72 B"]

В всписке должна быть цифра, которую мы запомнили для Ларри Эллисона.

finance.m[finance.m == "$41 B"]

Должно быть как минимум два значения, встречающихся несколько раз.

length(unique(finance.m))



### Задание 2


5. В данных доход представлен в формате "$42 B", что означает 42 × 10^9. Преобразуйте этот формат в числовой и
сохраните в вектор worths. Удостоверьтесь в следующем:

worths <- (as.numeric(gsub(",",".",regmatches(finance.m,regexpr("\\d{1,},\\d{1,} |\\d{1,}",finance.m)))))*10^9
worths


worths является вектором и в нём сто занчений типа double.

is.vector(worths)
length(worths)
typeof(worths)

Все элементы вектора worths больше 1 миллиарда.

length(worths[worths > 10^9])

Самое большое число это доход Билла Гейтса.

worths[worths==max(worths)]


6. Используйте вектор worths , чтобы выяснить следующее:

Какова медиана ста этих записей?

median(worths)

Средний доход?

mean(worths)

Как много людей из этого списка имеют доход больше 5млрд., 10, 25?

length(worths[worths>5*10^9])
length(worths[worths>10*10^9])
length(worths[worths>25*10^9])

Какой их общий доход?

sum(worths)

Какую долю от общего дохода, составляет пятёрка самых богатых.

sum(worths[1:5])/sum(worths)

Какую долю от общего дохода, составляют 20 самых богатых.

sum(worths[1:20])/sum(worths)

В данных федерального резерва США найдите показатель дохода всех домохозяйств (Household net worth) в
соответвующем году, какую долю общего дохода составляют 100 богатейших людей.

sum(worths)/(78.536*10^9)